=head1 NAME

Swagger2::Guides::CustomPlaceholder - Custom placeholders

=head2 OVERVIEW

The default placeholder type is the
L<standard placeholder|https://metacpan.org/pod/distribution/Mojolicious/lib/Mojolicious/Guides/Routing.pod#Standard-placeholders>,
meaning ":". This can be customized using C<x-mojo-placeholder> in the
API specification. The example in L</SYNOPSIS> will enforce a
L<relaxed placeholder|https://metacpan.org/pod/distribution/Mojolicious/lib/Mojolicious/Guides/Routing.pod#Relaxed-placeholders>.

=head1 SYNOPSIS

  {
    "swagger": "2.0",
    "basePath": "/api",
    "paths": {
      "/pets/{name}": {
        "get": {
          "operationId": "listPets",
          "parameters": [
            { "name": "name", "in": "path", "type": "string", "x-mojo-placeholder": "#" }
          ],
          "responses": {
            "200": { ... }
          }
        }
      }
    }
  }

=head1 AUTHOR

Jan Henning Thorsen - C<jhthorsen@cpan.org>

=cut
